In [1]:
import pandas as pd

In [2]:
data = pd.read_json('News_Category_Dataset_v3.json',lines=True)

In [3]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22


### Data Exploration

In [4]:
data.shape

(209527, 6)

In [5]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [6]:
data = data['short_description'].head(30000)

In [7]:
data

0        Health experts said it is too early to predict...
1        He was subdued by passengers and crew when he ...
2        "Until you have a dog you don't understand wha...
3        "Accidentally put grown-up toothpaste on my to...
4        Amy Cooper accused investment firm Franklin Te...
                               ...                        
29995    *Trigger Warning: Transphobia* Recently, Scary...
29996    The Olympian and reality star says she’s inter...
29997    Live every week like you don't have an actual ...
29998    Even Springsteen stops the show after three ho...
29999                                   We don't envy him.
Name: short_description, Length: 30000, dtype: str

In [8]:
data[0]

'Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall.'

In [9]:
data.isnull().sum()

np.int64(0)

In [10]:
data.duplicated().sum()

np.int64(154)

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.shape

(29846,)

### Data Prepration

In [14]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [15]:
tokenizer = Tokenizer(oov_token = '<OOV')

In [16]:
tokenizer.fit_on_texts(data)

In [17]:
tokenizer.word_index

{'<OOV': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'is': 8,
 'for': 9,
 'on': 10,
 'that': 11,
 'said': 12,
 'was': 13,
 'with': 14,
 'it': 15,
 'his': 16,
 'are': 17,
 'have': 18,
 'as': 19,
 'has': 20,
 'at': 21,
 'this': 22,
 'he': 23,
 'be': 24,
 'an': 25,
 'i': 26,
 'from': 27,
 'trump': 28,
 'not': 29,
 'you': 30,
 'president': 31,
 'by': 32,
 'about': 33,
 '”': 34,
 'but': 35,
 'new': 36,
 'will': 37,
 'who': 38,
 'her': 39,
 'after': 40,
 'one': 41,
 'people': 42,
 'we': 43,
 'their': 44,
 'more': 45,
 'been': 46,
 'they': 47,
 'out': 48,
 'up': 49,
 'all': 50,
 'year': 51,
 'what': 52,
 'u': 53,
 'she': 54,
 's': 55,
 'were': 56,
 'just': 57,
 'when': 58,
 'former': 59,
 'than': 60,
 'or': 61,
 'no': 62,
 'over': 63,
 'first': 64,
 'my': 65,
 'like': 66,
 'had': 67,
 'if': 68,
 'our': 69,
 'can': 70,
 'says': 71,
 'time': 72,
 'would': 73,
 'your': 74,
 'some': 75,
 'house': 76,
 'two': 77,
 'white': 78,
 'so': 79,
 "it's": 80,
 'into': 81,
 'how': 82,
 

#### Unique Token

In [18]:
len(tokenizer.word_index)

31983

In [19]:
data = tokenizer.texts_to_sequences(data)

In [20]:
data

[[140,
  401,
  12,
  15,
  8,
  154,
  531,
  3,
  6425,
  341,
  1641,
  73,
  2434,
  49,
  14,
  2,
  16575,
  213,
  4303,
  5,
  2,
  36,
  16576,
  2,
  53,
  55,
  1517,
  9,
  2,
  899],
 [23,
  13,
  16577,
  32,
  2615,
  6,
  2435,
  58,
  23,
  2125,
  3,
  2,
  110,
  5,
  2,
  3428,
  40,
  2,
  4304,
  275,
  3,
  2,
  53,
  55,
  8182,
  293,
  7,
  1050,
  1136],
 [565, 30, 18, 4, 1386, 30, 195, 1007, 52, 84, 24, 9685],
 [4033,
  304,
  4305,
  49,
  12060,
  10,
  65,
  16578,
  16579,
  6,
  23,
  12061,
  66,
  26,
  13,
  3813,
  16,
  3814,
  14,
  4,
  1286,
  16580,
  12062,
  7,
  16581,
  7164],
 [2059,
  3261,
  169,
  4034,
  1884,
  5817,
  16582,
  5,
  8183,
  2837,
  39,
  6,
  8184,
  39,
  4,
  782,
  40,
  225,
  5,
  2,
  1387,
  1008,
  2211,
  397,
  1035],
 [2,
  4306,
  51,
  104,
  215,
  13,
  482,
  391,
  21,
  2,
  408,
  1286,
  1597,
  10,
  694,
  54,
  13,
  232,
  474,
  360,
  40,
  39,
  201,
  434,
  39,
  990,
  453,
  12],
 [1388,

In [21]:
input_sequences = []
for seq in data:
    if len(seq)<2:
        continue
    for i in range(1,len(seq)):
        ngram = seq[:i+1]
        input_sequences.append(ngram)

### We are putting the condition if sentence is having less 2 words then skip such sentences 

In [22]:
input_sequences

[[140, 401],
 [140, 401, 12],
 [140, 401, 12, 15],
 [140, 401, 12, 15, 8],
 [140, 401, 12, 15, 8, 154],
 [140, 401, 12, 15, 8, 154, 531],
 [140, 401, 12, 15, 8, 154, 531, 3],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641, 73],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641, 73, 2434],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641, 73, 2434, 49],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641, 73, 2434, 49, 14],
 [140, 401, 12, 15, 8, 154, 531, 3, 6425, 341, 1641, 73, 2434, 49, 14, 2],
 [140,
  401,
  12,
  15,
  8,
  154,
  531,
  3,
  6425,
  341,
  1641,
  73,
  2434,
  49,
  14,
  2,
  16575],
 [140,
  401,
  12,
  15,
  8,
  154,
  531,
  3,
  6425,
  341,
  1641,
  73,
  2434,
  49,
  14,
  2,
  16575,
  213],
 [140,
  401,
  12,
  15,
  8,
  154,
  531,
  3,
  6425,
  341,
  1641,
  73,
  2434,
  49,
  14,
  2,
  16

In [23]:
max_len = max([len(i) for i in input_sequences])

In [24]:
max_len

78

In [25]:
input = pad_sequences(input_sequences,padding='pre',maxlen = max_len)

In [26]:
input

array([[    0,     0,     0, ...,     0,   140,   401],
       [    0,     0,     0, ...,   140,   401,    12],
       [    0,     0,     0, ...,   401,    12,    15],
       ...,
       [    0,     0,     0, ...,     0,    43,   195],
       [    0,     0,     0, ...,    43,   195, 16570],
       [    0,     0,     0, ...,   195, 16570,   100]],
      shape=(437399, 78), dtype=int32)

In [27]:
input[50]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,    23,    13, 16577,    32,  2615,     6,  2435,    58,
          23,  2125,     3,     2,   110,     5,     2,  3428,    40,
           2,  4304,   275,     3,     2,    53], dtype=int32)

In [28]:
X = input[:,:-1]
y = input[:,-1]

In [29]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 140],
      dtype=int32)

In [30]:
X.shape

(437399, 77)

In [31]:
y.shape

(437399,)

In [32]:
y=np.array(y)

### Modeling

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [35]:
X_train.shape

(349919, 77)

In [36]:
vocab_size = len(tokenizer.word_index)+1

In [37]:
vocab_size

31984

In [38]:
max_len = X.shape[1]

In [39]:
max_len

77

In [40]:
model = Sequential([Embedding(vocab_size, 128,input_length=max_len),LSTM(256),Dense(vocab_size,'softmax')])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [41]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [42]:
model.build(input_shape=(None,max_len))

In [43]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 77, 128)        │     4,093,952 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 31984)          │     8,219,888 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,708,080 (48.48 MB)

 Trainable params: 12,708,080 (48.48 MB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

Epoch 1/10
  927/10935 ━━━━━━━━━━━━━━━━━━━━ 52:38 316ms/step - accuracy: 0.0505 - loss: 8.3731

KeyboardInterrupt: 

In [ ]:
model.save('next_wrod_model.h5')

In [ ]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)